### ISSUE TITLE
Retrieving current user, logging him out

### ISSUE THREAD

**Issue by ashorlivs** [philiplb/CRUDlexUser#1]
Hi, do you have any hints on how these topics?
1. retrieve the current logged in user (other than `$_SERVER['PHP_AUTH_USER']`)
2. log him out  ([SecurityServiceProvider doc](http://silex.sensiolabs.org/doc/providers/security.html#accessing-the-current-user)'s method only works with `Forms`)?

**Comment by philiplb** [comment]
Hi,
you can put the logout-snipped at any place in a custom layout.
For the snippet and where a link should lead to: http://silex.sensiolabs.org/doc/providers/security.html#adding-a-logout

Just copy the layout.twig at some location into your own template folder and reference it:

```php
$app['crud.layout'] = 'myLayout.twig';
```

See http://philiplb.github.io/CRUDlex/docs/html/0.9.10/manual/layouts.html

**Comment by ashorlivs** [comment]
Thanks, but before posting the issue I tried following the doc but couldn't get it working. Since the `logout_path` must match the main firewall pattern, I tried to edit like this:

```
'security.firewalls' => array(
    'crud' => array(
        'pattern' => '^/crud/',
        'http' => true,
        'users' => $userProvider,
        'logout' => array('logout_path' => '/crud/logout', 'invalidate_session' => true)
    ),
)
```
```
<a href="{{ path('crud_logout') }}">Logout</a>
```

The logout link is generated but not has no effect (e.g. being on /crud/user and clicking the logout link redirects to homepage without loging out).

---

Off-topic: to override the templates I followed another method:
1. duplicate the existing views folder in /views/vendor/philiplb/crudlex/views
2. `$app['twig.loader.filesystem']->addPath(dirname(__DIR__).'/views/vendor/philiplb/crudlex/views', 'crud');`
More convenient for me than declaring the $app['crud.xxx'] paths.

**Comment by philiplb** [comment]
This is how we do it:
In the Firewall:
```php
'logout' => array(
    'logout_path' => '/user/logout',
),
```
And then just a dummy route as Symfony/Security takes care of the rest:

```php
$app->match('/user/logout', function () {
})->bind('user.logout');
```

In the template, you just link your logout button to this route.

**Comment by ashorlivs** [comment]
Thanks, well it's definitely not re-asking for user/password after clicking the link and being redirected to the homepage, then going back to /crud pages.
Tested with Chrome and FF under private mode. I've also tried to change my .htaccess according to http://silex.sensiolabs.org/doc/providers/security.html#securing-a-path-with-http-authentication (altought I'm not using php-cgi) but no luck :(
