### ISSUE TITLE
A better login page

### ISSUE THREAD

**Issue by Germain-Italic** [philiplb/CRUDlexUser#3]
Hi Phil,
According to you, what would be the smartest way to implement a login page instead of the http "realm" access pop-up?

Looking for guidance in securing with form: http://silex.sensiolabs.org/doc/providers/security.html#securing-a-path-with-a-form

**Comment by philiplb** [comment]
Hi,
I just wanted to give you this exact link. :) Is there anything unclear I can guide you with?

**Comment by philiplb** [comment]
Closing for now. Feel free to reopen if there is anything left.
