### ISSUE TITLE
Require Locale and Translation Service provider

### ISSUE THREAD

**Issue by dmaciel** [philiplb/CRUDlexUser#5]
Hi

I'm using CRUDlex and CRUDlexUser in a project, but to use CRUDlexUser I need to add the following:
$app->register(new Silex\Provider\LocaleServiceProvider());
$app->register(new Silex\Provider\TranslationServiceProvider(), array(
    'locale_fallbacks' => array('en'),
));

It's possible to use crudlex without requiring this?

**Comment by philiplb** [comment]
Hi,
this is a required provider and CRUDlex will initialize them, if this is not already done.
0.11.0 got a few fixes for this behaviour.
Feel free to reopen the issue if you have any more feedback or questions. :)
